select * from customer;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount)
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount > (select AVG(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating) :: numeric , 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
Order BY avg_review_rating DESC
LIMIT 5


-- Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type, AVG(purchase_amount)
FROM customer 
GROUP BY shippping_type;

-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, 
ROUND(AVG(purchase_amount),2) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY subscription_status


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND((100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*)),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5


-- Q7. Segment customers into New, Returning, and Loyal
-- based on their total number of previous purchases,
-- and show the count of each segment.
SELECT CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases >= 2 AND previous_purchases <=10 THEN 'Returning'
ELSE 'Loyal'
END AS customer_segment,
COUNT(customer_id)
FROM customer
GROUP BY customer_segment


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS items_per_category,
ROW_NUMBER() OVER (
	PARTITION BY category
	ORDER BY COUNT(customer_id) DESC
) AS rnk
FROM customer
GROUP BY category, item_purchased
)
SELECT rnk, category,
item_purchased, items_per_category
FROM item_counts
WHERE rnk <= 3

-- Q9. Are customers who are repeat buyers
-- (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status


-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS revenue_contribution
FROM customer
GROUP BY age_group
order by revenue_contribution DESC

